### ISSUE TITLE
Multi pass todo

### ISSUE THREAD

**Issue by lu-zero** [xiph/rav1e#2146]
- [ ] Make the first pass not do a full encoding and stop once the rate control information is available
- [ ] Save all the lookahead information in the rate-control data
- [ ] In the second pass skip the lookahead process and use the rate-control data instead.

**Comment by grill05** [comment]
This may be related to https://github.com/xiph/rav1e/issues/1959

**Comment by lu-zero** [comment]
It is. let me update
